# Render.com Blueprint for SurveyOnline
# This deploys the backend API and database
# Deploy the frontend separately as a Static Site

services:
  # Backend API Service
  - type: web
    name: surveyonline-api
    runtime: node
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npx prisma migrate deploy && npm run seed:prod && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: surveyonline-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: surveyonline-db
    databaseName: surveyonline
    user: surveyonline_user

# After deploying this blueprint, manually create a Static Site for the frontend:
# 1. New > Static Site
# 2. Connect same repository
# 3. Build command: cd client && npm install && npm run build
# 4. Publish directory: ./client/dist
# 5. Environment variable: VITE_API_URL=https://surveyonline-api.onrender.com
# 6. Redirect rule: /* -> /index.html (rewrite)

# Environment Variables Documentation
# The following environment variables will be automatically set:
# - NODE_ENV: Set to 'production' for the backend
# - PORT: Set to 10000 (Render's default)
# - JWT_SECRET: Auto-generated secure secret for JWT tokens
# - DATABASE_URL: Auto-generated PostgreSQL connection string
# - VITE_API_URL: Frontend API endpoint URL

# Deployment Notes:
# 1. The backend will automatically run Prisma migrations on first deploy
# 2. The frontend will be built as a static site with SPA routing
# 3. Database will be automatically provisioned and connected
# 4. SSL certificates will be automatically provided
# 5. Custom domains can be added in the Render dashboard