# Render.com Blueprint for SurveyOnline with Snowflake
# This deploys the backend API 
# Deploy the frontend separately as a Static Site

services:
  # Backend API Service
  - type: web
    name: surveyonline-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install && npm run build && npm run setup:db && npm run seed:prod
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SNOWFLAKE_ACCOUNT
        value: YOUR_SNOWFLAKE_ACCOUNT
      - key: SNOWFLAKE_USERNAME
        value: YOUR_SNOWFLAKE_USERNAME
      - key: SNOWFLAKE_PASSWORD
        value: YOUR_SNOWFLAKE_PASSWORD
      - key: SNOWFLAKE_DATABASE
        value: SURVEYONLINE
      - key: SNOWFLAKE_SCHEMA
        value: PUBLIC
      - key: SNOWFLAKE_WAREHOUSE
        value: COMPUTE_WH
      - key: SNOWFLAKE_ROLE
        value: ACCOUNTADMIN
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: FRONTEND_URL
        value: https://surveyonline-ln66.onrender.com

# After deploying this blueprint, manually create a Static Site for the frontend:
# 1. New > Static Site
# 2. Connect same repository
# 3. Build command: cd client && npm install && npm run build
# 4. Publish directory: ./client/dist
# 5. Environment variable: VITE_API_URL=https://surveyonline-api.onrender.com
# 6. Redirect rule: /* -> /index.html (rewrite)

# Environment Variables Documentation
# The following environment variables will be automatically set:
# - NODE_ENV: Set to 'production' for the backend
# - PORT: Set to 10000 (Render's default)
# - JWT_SECRET: Auto-generated secure secret for JWT tokens
# - SNOWFLAKE_*: Snowflake connection credentials (must be provided manually)
# - VITE_API_URL: Frontend API endpoint URL

# Deployment Notes:
# 1. The backend will automatically run database setup on first deploy
# 2. The frontend will be built as a static site with SPA routing
# 3. Snowflake database must be set up separately with proper credentials
# 4. SSL certificates will be automatically provided
# 5. Custom domains can be added in the Render dashboard