services:
  # Backend API Service
  - type: web
    name: surveyonline-api
    env: node
    plan: starter
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npx prisma migrate deploy && npm run seed:prod && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: surveyonline-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
    autoDeploy: true
    
  # Frontend Static Site
  - type: static
    name: surveyonline-frontend
    env: static
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://surveyonline-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: surveyonline-db
    databaseName: surveyonline
    user: surveyonline_user
    plan: starter

# Environment Variables Documentation
# The following environment variables will be automatically set:
# - NODE_ENV: Set to 'production' for the backend
# - PORT: Set to 10000 (Render's default)
# - JWT_SECRET: Auto-generated secure secret for JWT tokens
# - DATABASE_URL: Auto-generated PostgreSQL connection string
# - VITE_API_URL: Frontend API endpoint URL

# Deployment Notes:
# 1. The backend will automatically run Prisma migrations on first deploy
# 2. The frontend will be built as a static site with SPA routing
# 3. Database will be automatically provisioned and connected
# 4. SSL certificates will be automatically provided
# 5. Custom domains can be added in the Render dashboard